name = input("Enter your name: ")
city = input("Enter your city: ")
fav_food = input("Enter your fav food: ")
fav_movie = input("Enter your fav movie: ")
fav_place = input("Enter your fav place: ")
fav_sport = input("Enter your fav sport: ")
fav_color = input("Enter your fav color: ")
fav_car = input("Enter your fav car: ")
fav_bike = input("Enter your fav bike: ")
fav_sportsman = input("Enter your fav sportsman: ")

print("!!!!INFO!!!!")
print(f'{name=}')
print(f'{city=}')
print(f'{fav_food=}')
print(f'{fav_movie=}')
print(f'{fav_place=}')
print(f'{fav_sport=}')
print(f'{fav_color=}')
print(f'{fav_car=}')
print(f'{fav_bike=}')
print(f'{fav_sportsman=}')
